apiVersion: apps/v1
kind: Deployment
metadata:
  name: ezyevent-location-api-deployment
  labels:
    app: ezyevent-location-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ezyevent-location-api
  template:
    metadata:
      labels:
        app: ezyevent-location-api
    spec:
      containers:
        - name: ezyevent-location-api
          image: gcr.io/ezyevents/location-api:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ezyevent-location-api-service
  labels:
    app: ezyevent-location-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: ezyevent-location-api
  sessionAffinity: None
