apiVersion: v1
kind: Service
metadata:
  name: ezyevent-location-api-service
  labels:
    app: ezyevent-location-api
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: ezyevent-api
  sessionAffinity: None
